### ISSUE TITLE
JODC Logo

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc-website-deprecated#11]
1. Add JODC logo to the web page.

2. Replace OSI logo with JODC mascot.
As mascot is not ready yet, replace it with JODC logo temporarily.
Note- Check licenses and permissions before using such logos.

**Comment by im-gozmit** [comment]
@Ankk98  Provide the link for the logo.

**Comment by im-gozmit** [comment]
@weirdwiz  can you Just put up the logo and host your site somewhere and send us the link ?
Netlify is good for hosting :+1:

**Comment by weirdwiz** [comment]
@im-gozmit this is actually not an image just computer generated ascii 
link : http://patorjk.com/software/taag/#p=display&f=3D-ASCII&t=JODC

**Comment by Ankk98** [comment]
We need a modification on the logo, I will give links to modified logo as soon it is modified.

**Comment by arvindpunk** [comment]
> We need a modification on the logo, I will give links to modified logo as soon it is modified.

I can help with that, I've got the original logo file.

**Comment by arvindpunk** [comment]
[There](https://imgur.com/a/OIGbmhN), in 3 different sizes. Ping me if you need it even larger.

**Comment by Ankurk99** [comment]
Any update on logo?

**Comment by Ankk98** [comment]
@arvindpunk 
Can you modify the logo to match with the background and add it to the website?

**Comment by weirdwiz** [comment]
@Ankk98 i think it is transparent, @arvindpunk can you upload this on dropbox/gdrive? cause imgur compresses image a lot

**Comment by prox07** [comment]
@arvindpunk?

**Comment by Ankk98** [comment]
@weirdwiz 
Here is the link to the JODC logo.
Feel free to experiment with it and show creativity to make it better.

https://github.com/JIITODC/jodc-logo

**Comment by Ankurk99** [comment]
Replaced OSI logo with JODC logo till we have a new logo refer ISSUE #93
