### ISSUE TITLE
Section of Members

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc-website-deprecated#2]
Add a section with short info about members

**Comment by elsonlim** [comment]
Would like to take a stab at this! Do you have the list of members? Right now, I'm implementing it using the github contributors of this repo.

**Comment by Ankk98** [comment]
@elsonlim Sure, you can work on it.
Just implement the reviewed changes.

**Comment by prox07** [comment]
@elsonlim Can you implement a way such that this section updates automatically? That'd be in my opinion far more efficient approach than hardcoding each contributor's name and image every now and then.

We'd really love if you go the extra mile here. Kudos!

**Comment by Ankk98** [comment]
@im-gozmit @octamois @amanharitsh123 @prox07 @koderjoker @VARoDeK @triptishukla 
Write your short intros and your story in open source community and mail to jiitodc@gmail.com for the website.

**Comment by AasthaGoyal** [comment]
If you want the Members to be updated automatically, u can save the photos, the name and the stories of the members in a database and show the data from a database on the page. This way, in case one has to add a member or remove it, you can just change it in the database, upload a photo and it would automatically be changed on the webpage.

**Comment by rexagod** [comment]
Hey @AasthaGoyal! This repository has been, as is dicernable from the title itself, deprecated. Although we soon will start work on a new repository for a website, do check it out then!

Thanks for your interest.
