### ISSUE TITLE
Events Sections

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc-website-deprecated#3]
Add a section for past events, workshops etc.
And about future workshops.

**Comment by triptishukla** [comment]
@Ankk98 Shouldn't we add a timeline to this section? It would look great.

**Comment by prox07** [comment]
@triptishukla Please do!

**Comment by Ankk98** [comment]
@triptishukla Yeah, that's a nice idea.

**Comment by Ankk98** [comment]
@triptishukla 
Work on it.

**Comment by Ankk98** [comment]
@triptishukla Also add information about past events in this section now as you are aware of them.
