### ISSUE TITLE
Resources Section

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc-website-deprecated#7]
Section for:

1. How to start with open source?
2. Why open source?
3. How to get started with Linux?
4. Git/Github - Collaboration
5. IRC - Networking
6. Meetups
7. Hackathons/Competitions
8. Outreach programs like GSoC
9. Open source licenses
10. Others

Suggestions and contributions are always welcome!

**Comment by Ankk98** [comment]
For documentation, resources and guides we can use:
readthedocs.io

**Comment by Ri2parna** [comment]
Can I work on it?

**Comment by prox07** [comment]
@Ri2parna Please do.
