### ISSUE TITLE
Projects Section

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc-website-deprecated#9]
A section for projects that have been made and for projects that are currently going on.
With a link on how to contribute.

**Comment by Ri2parna** [comment]
Any details on so on as what projects are going on?

**Comment by Ankk98** [comment]
@Ri2parna 
Right now you can start by making a template and add "Coming soon" to them.
You can also add JODC website as a project.

**Comment by prox07** [comment]
@Ri2parna **Is there any progress whatsoever on the matter?**

**Comment by Ri2parna** [comment]
Okay, I am working on it.

**Comment by Ri2parna** [comment]
How much time do I have.I have exams and I needed to study? can't it wait till monday?

**Comment by Ankk98** [comment]
We have targets for Sunday, so Sunday is the last we can wait for it.
